config/routes.rb
Rails.application.routes.draw do
  resources :students

end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:nameofstu, :nameofuniversity, :telnumer, :emailofstu, :addressofstu, :birthday, :graduate, :dayoftoroku, :dayofentrysheet, :dayofraisya, :memoofstu)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Product1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nameofstu %><br>
    <%= f.text_field :nameofstu %>
  </div>
  <div class="field">
    <%= f.label :nameofuniversity %><br>
    <%= f.text_field :nameofuniversity %>
  </div>
  <div class="field">
    <%= f.label :telnumer %><br>
    <%= f.text_field :telnumer %>
  </div>
  <div class="field">
    <%= f.label :emailofstu %><br>
    <%= f.text_field :emailofstu %>
  </div>
  <div class="field">
    <%= f.label :addressofstu %><br>
    <%= f.text_field :addressofstu %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday %>
  </div>
  <div class="field">
    <%= f.label :graduate %><br>
    <%= f.text_field :graduate %>
  </div>
  <div class="field">
    <%= f.label :dayoftoroku %><br>
    <%= f.date_select :dayoftoroku %>
  </div>
  <div class="field">
    <%= f.label :dayofentrysheet %><br>
    <%= f.date_select :dayofentrysheet %>
  </div>
  <div class="field">
    <%= f.label :dayofraisya %><br>
    <%= f.text_field :dayofraisya %>
  </div>
  <div class="field">
    <%= f.label :memoofstu %><br>
    <%= f.text_field :memoofstu %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <thead>
    <tr>
      <th>Nameofstu</th>
      <th>Nameofuniversity</th>
      <th>Telnumer</th>
      <th>Emailofstu</th>
      <th>Addressofstu</th>
      <th>Birthday</th>
      <th>Graduate</th>
      <th>Dayoftoroku</th>
      <th>Dayofentrysheet</th>
      <th>Dayofraisya</th>
      <th>Memoofstu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.nameofstu %></td>
        <td><%= student.nameofuniversity %></td>
        <td><%= student.telnumer %></td>
        <td><%= student.emailofstu %></td>
        <td><%= student.addressofstu %></td>
        <td><%= student.birthday %></td>
        <td><%= student.graduate %></td>
        <td><%= student.dayoftoroku %></td>
        <td><%= student.dayofentrysheet %></td>
        <td><%= student.dayofraisya %></td>
        <td><%= student.memoofstu %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nameofstu:</strong>
  <%= @student.nameofstu %>
</p>

<p>
  <strong>Nameofuniversity:</strong>
  <%= @student.nameofuniversity %>
</p>

<p>
  <strong>Telnumer:</strong>
  <%= @student.telnumer %>
</p>

<p>
  <strong>Emailofstu:</strong>
  <%= @student.emailofstu %>
</p>

<p>
  <strong>Addressofstu:</strong>
  <%= @student.addressofstu %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @student.birthday %>
</p>

<p>
  <strong>Graduate:</strong>
  <%= @student.graduate %>
</p>

<p>
  <strong>Dayoftoroku:</strong>
  <%= @student.dayoftoroku %>
</p>

<p>
  <strong>Dayofentrysheet:</strong>
  <%= @student.dayofentrysheet %>
</p>

<p>
  <strong>Dayofraisya:</strong>
  <%= @student.dayofraisya %>
</p>

<p>
  <strong>Memoofstu:</strong>
  <%= @student.memoofstu %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>